services:
  postgres-dev:
    profiles: ['dev']
    image: postgres:16-alpine
    container_name: vinyle_postgres_dev
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U strapi_user -d strapi_vinyle_db']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  pgadmin:
    profiles: ['dev']
    image: dpage/pgadmin4:latest
    container_name: vinyle_pgadmin
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - '5050:80'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres-dev:
        condition: service_healthy

  postgres-prod:
    profiles: ['prod']
    image: postgres:16-alpine
    container_name: vinyle_postgres_prod
    restart: always
    env_file:
      - ./backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U strapi_user -d strapi_vinyle_db']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local
